import os
from typing import Optional

from pydantic_settings import BaseSettings as PydanticBaseSettings

ENV_FILE = os.getenv("ENV_FILE", ".env")


class BaseSettings(PydanticBaseSettings):
    """Base class for loading settings.

    The setting variables are loaded from environment settings first, then from the defined env_file.
    Different groups/contexts of settings are created using different classes, that can define an env_prefix
    which will be concatenated to the start of the variable name.
    """

    class Config:
        env_file = ENV_FILE
        extra = "ignore"


class APISettings(BaseSettings):
    """Settings related with the FastAPI server"""
    host: str = "0.0.0.0"
    port: int = 5000

    class Config(BaseSettings.Config):
        env_prefix = "API_"


class DatabaseSettings(BaseSettings):
    """Settings related with the database connection"""
    postgres_db: Optional[str] = None
    postgres_user: Optional[str] = None
    postgres_password: Optional[str] = None
    postgres_port: int = 5432
    database_url: Optional[str] = None

    class Config(BaseSettings.Config):
        env_prefix = ""

    @property
    def sqlalchemy_url(self) -> str:
        """Return the configured async DB URL or build it from individual fields."""
        if self.database_url:
            return self.database_url

        missing = [
            name for name, value in (
                ("postgres_db", self.postgres_db),
                ("postgres_user", self.postgres_user),
                ("postgres_password", self.postgres_password),
            )
            if not value
        ]
        if missing:
            raise RuntimeError(
                "Database configuration is incomplete. Set either DATABASE_URL "
                "or the following variables: postgres_db, postgres_user, postgres_password."
            )

        return (
            f"postgresql+asyncpg://{self.postgres_user}:{self.postgres_password}"
            f"@localhost:{self.postgres_port}/{self.postgres_db}"
        )

    @property
    def alembic_url(self) -> str:
        """Return a synchronous DB URL for Alembic migrations."""
        if self.database_url:
            return self.database_url.replace("postgresql+asyncpg://", "postgresql+psycopg://")

        missing = [
            name for name, value in (
                ("postgres_db", self.postgres_db),
                ("postgres_user", self.postgres_user),
                ("postgres_password", self.postgres_password),
            )
            if not value
        ]
        if missing:
            raise RuntimeError(
                "Database configuration is incomplete. Set either DATABASE_URL "
                "or the following variables: postgres_db, postgres_user, postgres_password."
            )

        return (
            f"postgresql+psycopg://{self.postgres_user}:{self.postgres_password}"
            f"@localhost:{self.postgres_port}/{self.postgres_db}"
        )


class APIDocsSettings(BaseSettings):
    """Settings related with the API autogenerated documentation"""
    title: str = "expeditions-app"
    """Title of the API"""
    description: Optional[str] = None
    """Description of the API"""
    version: str = "version"

    class Config(BaseSettings.Config):
        env_prefix = "API_DOCS_"


class RequestLoggingSettings(BaseSettings):
    """Settings related with the logging of requests"""
    level: str = "DEBUG"
    serialize: bool = False

    class Config(BaseSettings.Config):
        env_prefix = "REQUEST_LOG_"


api_settings = APISettings()
database_settings = DatabaseSettings()
api_docs_settings = APIDocsSettings()
request_logging_settings = RequestLoggingSettings()